Project Code/Unravel_Bangladesh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',include('homepage.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^menu/',include('menu.urls')),
    url(r'^tour/',include('tour.urls')),
    url(r'^community/', include('community.urls')),
    url(r'^payments/',  include('payments.urls')),

]

Project Code/menu/urls.py
from django.conf.urls import url
from menu import views

app_name= 'menu'

urlpatterns=[
    url(r'^$',views.menu,name='menu'),

]

Project Code/tour/urls.py
from django.conf.urls import url
from tour import views
app_name = 'tour'
urlpatterns =[
    url(r'^sylhet/$',views.sylhet,name='sylhet'),
    url(r'^barisal/$',views.barisal,name='barisal'),
    url(r'^rajshahi/$',views.rajshahi,name='rajshahi'),
    url(r'^saint_martin/$',views.saint_martin,name='saint_martin'),
    url(r'^khulna/$',views.khulna,name='khulna'),
    url(r'^chittagong/$',views.chittagong,name='chittagong'),
    url(r'^dhaka/$',views.dhaka,name='dhaka'),

    url(r'^syl/$',views.syl,name='syl'),
    url(r'^khu/$',views.khu,name='khu'),
    url(r'^bar/$',views.bar,name='bar'),
    url(r'^raj/$',views.raj,name='raj'),
    url(r'^dhk/$',views.dhk,name='dhk'),
    url(r'^ctg/$',views.ctg,name='ctg'),
    url(r'^map/$',views.map,name='map'),
    url(r'^hotel/$',views.hotel,name='hotel'),


]

Project Code/tour/views.py
from django.shortcuts import render


def sylhet(request):
    return render(request,'tour/Sylhet.html')



def barisal(request):
    return render(request, 'tour/Barisal.html')


def rajshahi(request):
    return render(request,'tour/Rajshahi.html')




def saint_martin(request):
    return render(request, 'tour/Saint Martin.html')

def khulna(request):
    return render(request,'tour/Khulna.html')

def chittagong(request):
    return render(request,'tour/Chittagong.html')

def dhaka(request):
    return render(request,'tour/Dhaka.html')


def syl(request):
    return render(request, 'tour/syl_log.html')

def dhk(request):
    return render(request,'tour/dhk_log.html')

def ctg(request):
    return render(request,'tour/ctg_log.html')

def bar(request):
    return render(request,'tour/bar_log.html')

def raj(request):
    return render(request,'tour/raj_log.html')

def khu(request):
    return render(request,'tour/khu_log.html')


def map(request):
    return render(request,'tour/map.html')

def hotel(request):
    return render(request,'tour/hotel.html')

Project Code/templates/tour/Chittagong.html
{% extends 'tour/tour_base.html' %}
{% load staticfiles %}

{% block title_M %}
<div id="title" class="slide header">
<style>
    #title{
        background-image: url("https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/The_Shah_Amanat_Bridge.jpg/1024px-The_Shah_Amanat_Bridge.jpg");
    }
</style>

     <button onclick="location.href='{% url 'tour:ctg' %}'" class="custom-btn btn-4" style="font-size: 42px;color:white;margin-top: 140px;"><span><b>C H I T T A G O N G</b></span></button></a>

</div>

{% endblock %}

 {% block slide1 %}
     <div id="slide1" class="slide">
    <div class="title">
        <style>
            #slide1:before {
  background-image: url("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Sunset_at_Patenga_beach.jpg/600px-Sunset_at_Patenga_beach.jpg.jpg");
}
        </style>
     <h1>Patenga</h1>
     <p>Sea Beach, Mesmerizing</p>
    </div>
     </div>
{% endblock %}

 {% block slide2 %}


<div id="slide2" class="slide">
<style>
     #slide2 {
    background-image: url("http://offroadbangladesh.com/wp-content/uploads/2015/02/Foys-Lake-by-Pankaj-Barua-626x365.jpg") !important;
}
     </style>
    <div class="title">
        <h1>Foy's Lake</h1>
        <p>Lake, Park, Garden.</p>
    </div>
    <img src="https://i.imgur.com/kXZGwkz.jpg">
    <img src="https://www.up10s.com/2019/05/foys-lake.html">
</div>

{% endblock %}

 {% block slide3 %}
     <style>
     #slide3:before {
    background-image: url("http://www.ciu.edu.bd/icaict2016/images/war-cemetery.jpg");
}
     </style>
     <div id="slide3" class="slide">
    <div class="title">
     <h1>War Cemetry</h1>
    <p>Graveyard, quite, picturesque</p>
    </div>
     </div>
{% endblock %}


{% block slide4 %}
    <div id="slide4" class="slide header">
        <button onclick="location.href='{% url 'home' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>C o m m u n i t y</b></span></button>

        <button onclick="location.href='{% url 'tour:map' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>M a p</b></span></button>

        <button onclick="location.href='{%url 'tour:hotel'%}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>R e s e r v a t i o n s</b></span></button>

    </div>
{% endblock %}

Project Code/templates/tour/Dhaka.html
{% extends 'tour/tour_base.html' %}
{% load staticfiles %}

{% block title_M %}
<div id="title" class="slide header">
<style>
    #title{
        background-image: url("https://wallpapercave.com/wp/wp2298962.jpg");
    }
</style>

     <button onclick="location.href='{% url 'tour:dhk' %}'" class="custom-btn btn-4" style="font-size: 42px;color:white;margin-top: 140px;"><span><b>D H A K A</b></span></button></a>

</div>

{% endblock %}

 {% block slide1 %}
     <div id="slide1" class="slide">
    <div class="title">
        <style>
            #slide1:before {
  background-image: url("http://connecttask.com/wp-content/uploads/2013/02/amor-ekushe-international-mother-language-day257316_2573161.jpg");
}
        </style>
     <h1>Shahid Minar</h1>
     <p>National Monument</p>
    </div>
     </div>
{% endblock %}

 {% block slide2 %}


<div id="slide2" class="slide">
<style>
     #slide2 {
    background-image: url("https://photorator.com/photos/images/national-parliament-house-dhaka-bangladesh-architect-louis-kahn--85430.jpg") !important;
}
     </style>
    <div class="title">
        <h1>Jatiya Sangsad Bhaban</h1>
        <p>parliament house, Legislative complex.</p>
    </div>
    <img src="https://www.virtualbangladesh.com/wp-content/uploads/2014/10/pd58dy16.bmp">
    <img src="http://old.unb.com.bd/media/2017-06-29-14-14-07-06_9920.jpg">
</div>

{% endblock %}

 {% block slide3 %}
     <style>
     #slide3:before {
    background-image: url("https://4.bp.blogspot.com/-uruhkEkEde8/WrJEjcJA-oI/AAAAAAAAA3U/gwWLrxO7cn81bbiRgg7qPf7AYxToiLYEACLcBGAs/s640/13321647_815233685277343_5231224965604240560_n.jpg");
}
     </style>
     <div id="slide3" class="slide">
    <div class="title">
     <h1>Biman Bahini Jaadughor</h1>
    <p>Airforce Museum, first aircraft</p>
    </div>
     </div>
{% endblock %}

{% block slide4 %}
    <div id="slide4" class="slide header">
        <button onclick="location.href='{% url 'home' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>C o m m u n i t y</b></span></button>

        <button onclick="location.href='{% url 'tour:map' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>M a p</b></span></button>

        <button onclick="location.href='{%url 'tour:hotel'%}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>R e s e r v a t i o n s</b></span></button>

    </div>
{% endblock %}

Project Code/templates/tour/Rajshahi.html
{% extends 'tour/tour_base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/tour_base.css' %}">
    <title>Unravel Bangladesh</title>
</head>

{% block title_M %}
<div id="title" class="slide header">
<style>
    #title{
        background-image: url("https://cmxpv89733.i.lithium.com/t5/image/serverpage/image-id/298112iB81302DCFC2DFC3B/image-size/large?v=1.0&px=999");
    }
</style>

    <button onclick="location.href='{% url 'tour:raj' %}'" class="custom-btn btn-4" style="font-size: 42px;color:white;margin-top: 140px;"><span><b>R A J S H A H I</b></span></button></a>

</div>

{% endblock %}

 {% block slide1 %}
     <div id="slide1" class="slide">
    <div class="title">
        <style>
            #slide1:before {
  background-image: url("https://i.pinimg.com/originals/bf/9f/36/bf9f36aad380d6805a3a1fc25118dc14.jpg");
}
        </style>
     <h1>The Padma</h1>
     <p>The mighty one</p>
    </div>
     </div>
{% endblock %}



<div id="slide2" class="slide">
<style>
     #slide2 {
    background-image: url("https://live.staticflickr.com/2927/14153727600_903b4cd542_b.jpg") !important;
}
     </style>
    <div class="title">
        <h1>Bagha Mosque</h1>
        <p>The Ancient Architectural Masterpiece</p>
    </div>
    <img src="http://en.banglapedia.org/images/a/a7/BaghaMosque.jpg">
    <img src="http://offroadbangladesh.com/wp-content/uploads/2015/02/bagha-mosque-shameem-bakhshi1-626x365.jpg">
</div>


 {% block slide3 %}
     <style>
     #slide3:before {
    background-image: url("https://www.bdtravelguides.com/wp-content/uploads/puthia-shiva-temple-rajshahi-750x350.jpg");
}
     </style>
     <div id="slide3" class="slide">
    <div class="title">
     <h1>Puthia Shiva Temple</h1>
    <p>Architectural beauty with a sacred value</p>
    </div>
     </div>
{% endblock %}


{% block slide4 %}
    <div id="slide4" class="slide header">
        <button onclick="location.href='{% url 'home' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>C o m m u n i t y</b></span></button>

        <button onclick="location.href='{% url 'tour:map' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>M a p</b></span></button>

        <button onclick="location.href='{%url 'tour:hotel'%}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>R e s e r v a t i o n s</b></span></button>

    </div>
{% endblock %}

Project Code/templates/tour/Saint Martin's.html
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/tour_base.css' %}">
    <title>Unravel Bangladesh</title>
</head>

<video autoplay muted loop id="myVideo">
 <source src="{% static 'videos/SM.mp4' %}" type='video/mp4'>
  Your browser does not support HTML5 video.
</video>

<div class="content">
  <h1>Saint Martin</h1>
  <p style="color: white">Breathtaking beauty has a new name, Saint Martin. The magnificent beauty of this place never fails to amaze anyone. Your mind & soul will surely find its peace in the soothing site of this amazing place. Route-> Dhaka -> Chittagon->teknaf->Saint Martin. Best time - Januray to april .Type - Family/Friends</p>
</div>

Project Code/templates/tour/Sylhet.html
{% extends 'tour/tour_base.html' %}
{% load staticfiles %}

{% block title_M %}
<div id="title" class="slide header">
<style>
    #title{
        background-image: url("https://pix10.agoda.net/geo/city/513022/1_513022_02.jpg?s=1920x822");
    }
</style>

     <button onclick="location.href='{% url 'tour:syl' %}'" class="custom-btn btn-4" style="font-size: 42px;color:white;margin-top: 140px;"><span><b>S Y L H E T</b></span></button></a>

</div>

{% endblock %}

 {% block slide1 %}
     <div id="slide1" class="slide">
    <div class="title">
        <style>
            #slide1:before {
  background-image: url("https://i.ytimg.com/vi/4pDHeF0wzqI/maxresdefault.jpg");
}
        </style>
     <h1>Bichhanakandi</h1>
     <p>Mesmerizing, Amazing & Fascinating</p>
    </div>
     </div>
{% endblock %}

 {% block slide2 %}


<div id="slide2" class="slide">
<style>
     #slide2 {
    background-image: url("https://compote.slate.com/images/fa85d6c9-233f-4dd9-9783-66d13803965c.jpg") !important;
}
     </style>
    <div class="title">
        <h1>Ratargul</h1>
        <p>Soothing experience.</p>
    </div>
    <img src="https://assetsds.cdnedge.bluemix.net/sites/default/files/beta2/uploads/2013/08/ct05.jpg">
    <img src="https://live.staticflickr.com/8172/7943783096_243aa5ff85_b.jpg">
</div>

{% endblock %}

 {% block slide3 %}
     <style>
     #slide3:before {
    background-image: url("https://thetouristplace.com/wp-content/uploads/2017/05/Sylhet-Jaflong.jpg");
}
     </style>
     <div id="slide3" class="slide">
    <div class="title">
     <h1>Jaflong</h1>
    <p>Ferociously Beautiful</p>
    </div>
     </div>
{% endblock %}


{% block slide4 %}
    <div id="slide4" class="slide header">
        <button onclick="location.href='{% url 'home' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>C o m m u n i t y</b></span></button>

        <button onclick="location.href='{% url 'tour:map' %}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>M a p</b></span></button>

        <button onclick="location.href='{%url 'tour:hotel'%}'" class="custom-btn btn-4"
                style="font-size: 25px;color:white;margin-top: 140px;"><span><b>R e s e r v a t i o n s</b></span></button>

    </div>
{% endblock %}

Project Code/templates/tour/bar_log.html
{% extends 'tour/log_base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/log_base.css' %}">

    <title>Unravel Bangladesh</title>
</head>

{% block main1 %}
<section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://blog.amarroom.com/wp-content/uploads/2019/06/Guthia_mosqueBarisal.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Ghutia Mosque</h1><p>Aesthetically pleasing, Religiously soothing</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Ghutia Mosque</h4>
                   <p class="card-text"><b>Best Time to Go</b> - Whole Year<br><b>Route</b>- Barisal town -> Ghutia Mosque<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>

   
{% endblock %}


{% block main2 %}
    <section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://travelon24.com/wp-content/uploads/2018/05/sorupkathi-vasomanbazzar.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Swarupkathi</h1><p>The venice of Bangladesh.</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Ratargul</h4>
                  <p class="card-text"><b>Best Time to Go</b> - september to january<br><b>Route</b>- Barisal -> Swarupkathi->Peyara Bazar<br><b>Type</b> -Friends</p>
               </div>
               <div class="card-footer">
                  <button  onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>
{% endblock %}


{% block main3 %}
    <section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://i.redd.it/7gg9o4kqskv21.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Uzirpur</h1><p>Beauty has a new place</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Jaflong</h4>
                  <p class="card-text"><b>Best Time to Go</b> - may to september<br><b>Route</b>- Barisal -> Uzirpur<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button  onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>
{% endblock %}

Project Code/templates/tour/ctg_log.html
{% extends 'tour/log_base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/log_base.css' %}">

    <title>Unravel Bangladesh</title>
</head>

{% block main1 %}
<section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Sunset_at_Patenga_beach.jpg/600px-Sunset_at_Patenga_beach.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Patenga</h1><p>Mesmerizing, Amazing & Fascinating</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Patenga</h4>
                   <p class="card-text"><b>Best Time to Go</b> - Whole year<br><b>Route</b>- Chittagong -> Karnaphuli River -> Patenga<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>

   
{% endblock %}


{% block main2 %}
    <section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="http://offroadbangladesh.com/wp-content/uploads/2015/02/Foys-Lake-by-Pankaj-Barua-626x365.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Foy's Lake</h1><p>Lake, Park, Garden.</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Foy's Lake</h4>
                  <p class="card-text"><b>Best Time to Go</b> - Whole Year<br><b>Route</b>- Chittagong ->Foy's Lake<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'"  class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>
{% endblock %}


{% block main3 %}
    <section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="http://www.ciu.edu.bd/icaict2016/images/war-cemetery.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">War Cemetry</h1><p>Ferociously Beautiful</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">War Cemetry</h4>
                  <p class="card-text"><b>Best Time to Go</b> - Whole year<br><b>Route</b>- Chittagong -> Badshah Miya Chowdhury Road ->War Cemetry<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'"  class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>
{% endblock %}

Project Code/templates/tour/khu_log.html
{% extends 'tour/log_base.html' %}
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/log_base.css' %}">

    <title>Unravel Bangladesh</title>
</head>

{% block main1 %}
<section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/17/7d/00/cf/unesco-world-heritages.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Shait Gambud Mosque</h1><p>Landmark,Sacred & Religios Site</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Shait Gambud Mosque</h4>
                   <p class="card-text"><b>Best Time to Go</b> - Whole Year<br><b>Route</b>- Khulna -> Bagerhat -> Shait Gambud Mosque<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>

   
{% endblock %}


{% block main2 %}
    <section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://www.toursntripsbd.com/wp-content/uploads/2016/07/PB110823.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Sundarban</h1><p>Thrills of Adventure.</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Sundarban</h4>
                  <p class="card-text"><b>Best Time to Go</b> - Whole Year<br><b>Route</b>- Khulna -> Bagerhat -> Sundarban<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>
{% endblock %}


{% block main3 %}
    <section class="container">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <div class="row m-3">
         <div class="m-auto col col-12 col-sm-12 col-md-4">
            <div class="card">
               <div class="card-header">
                  <img class="card-img-top" src="https://a4.pbase.com/o6/93/586793/1/120907482.OnTTG08l.bangladeshBangladesh083.jpg" alt="">
                  <div class="floating-title"><h1 class="mt-3">Mongla Port</h1><p>SeaPort, Eye catcher</p></div>
               </div>
               <div class="card-body">
                  <h4 class="card-title">Mongla Port</h4>
                  <p class="card-text"><b>Best Time to Go</b> - Whole Year<br><b>Route</b>- Khulna -> Mongla -> Mongla Port<br><b>Type</b> - Family//Friends</p>
               </div>
               <div class="card-footer">
                  <button onclick="location.href='{%url 'tour:hotel'%}'" class="btn btn-success"style="background-color: black">R e s e r v a t i o n s</button>
               </div>
            </div>
         </div>
            </div>
         </div>
      </div>
   </section>
{% endblock %}