Project Code/Unravel_Bangladesh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',include('homepage.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^menu/',include('menu.urls')),
    url(r'^tour/',include('tour.urls')),
    url(r'^community/', include('community.urls')),
    url(r'^payments/',  include('payments.urls')),

]

Project Code/accounts/urls.py
from django.conf.urls import url
from accounts import views
# SET THE NAMESPACE!
app_name = 'accounts'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

Project Code/menu/urls.py
from django.conf.urls import url
from menu import views

app_name= 'menu'

urlpatterns=[
    url(r'^$',views.menu,name='menu'),

]

Project Code/tour/urls.py
from django.conf.urls import url
from tour import views
app_name = 'tour'
urlpatterns =[
    url(r'^sylhet/$',views.sylhet,name='sylhet'),
    url(r'^barisal/$',views.barisal,name='barisal'),
    url(r'^rajshahi/$',views.rajshahi,name='rajshahi'),
    url(r'^saint_martin/$',views.saint_martin,name='saint_martin'),
    url(r'^khulna/$',views.khulna,name='khulna'),
    url(r'^chittagong/$',views.chittagong,name='chittagong'),
    url(r'^dhaka/$',views.dhaka,name='dhaka'),

    url(r'^syl/$',views.syl,name='syl'),
    url(r'^khu/$',views.khu,name='khu'),
    url(r'^bar/$',views.bar,name='bar'),
    url(r'^raj/$',views.raj,name='raj'),
    url(r'^dhk/$',views.dhk,name='dhk'),
    url(r'^ctg/$',views.ctg,name='ctg'),
    url(r'^map/$',views.map,name='map'),
    url(r'^hotel/$',views.hotel,name='hotel'),


]

Project Code/menu/views.py
from django.shortcuts import render


def menu(request):
    return render(request,'menu/menu.html')

Project Code/templates/menu/menu.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <title>Destination</title>
</head>
<body>

{% block body_block %}
<div id="bt">
    {% if user.is_authenticated %}
         <p align="top-right"> <a href="{% url 'accounts:register' %}" style="padding:0px;
font-size: 16px;
color: white;
text-align:center;
position: absolute;
top: 10px;
right: 10px;;z-index: 1">{{ user.username }}</a> </p>
    {% else %}
        <p align="top-right"> <a href="{% url 'accounts:register' %}" style="padding:0px;
font-size: 16px;
color: white;
text-align:center;
position: absolute;
top: 10px;
right: 10px;;z-index: 1">SignIn||SignUp</a> </p>
    {% endif %}
</div>
{% endblock %}

<div id="vid">
<video autoplay muted loop id="myVideo">
  <source src="{% static 'videos/videoplayback.mp4' %}" type='video/mp4'>
  Your browser does not support HTML5 video.
</video>
</div>

<div class="header1">
    <h2 align="center"style="font-family:'Agency FB';font-size: 32px ;margin: 1px"><b>Unravel Bangladesh</b></h2>
</div>


 <ul>
        <li><a href="{% url 'tour:dhaka' %}">Dhaka</a></li>
        <li><a href="{% url 'tour:chittagong' %}">Chittagong</a></li>
        <li><a href="{% url 'tour:khulna' %}">Khulna</a></li>
        <li><a href="{% url 'tour:saint_martin' %}">Saint_Martin's</a></li>
        <li><a href="{% url 'tour:rajshahi'%}">Rajshahi</a></li>
        <li><a href="{% url 'tour:barisal' %}">Barisal</a></li>
        <li><a href="{% url 'tour:sylhet' %}">Sylhet</a></li>
    </ul>

</body>
</html>