Project Code/Unravel_Bangladesh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',include('homepage.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^menu/',include('menu.urls')),
    url(r'^tour/',include('tour.urls')),
    url(r'^community/', include('community.urls')),
    url(r'^payments/',  include('payments.urls')),

]

Project Code/accounts/urls.py
from django.conf.urls import url
from accounts import views
# SET THE NAMESPACE!
app_name = 'accounts'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

Project Code/community/urls.py
from django.urls import path
from django.conf.urls import url
from community import views

urlpatterns = [
    url(r'^PostList/$', views.PostList.as_view(), name='home'),
    url(r'^post_new/$', views.post_new, name='post_new'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

Project Code/homepage/urls.py
from django.conf.urls import url
from homepage import views

app_name = "homepage"
urlpatterns =[
    url(r'^$',views.index,name='index')

]

Project Code/menu/urls.py
from django.conf.urls import url
from menu import views

app_name= 'menu'

urlpatterns=[
    url(r'^$',views.menu,name='menu'),

]

Project Code/tour/urls.py
from django.conf.urls import url
from tour import views
app_name = 'tour'
urlpatterns =[
    url(r'^sylhet/$',views.sylhet,name='sylhet'),
    url(r'^barisal/$',views.barisal,name='barisal'),
    url(r'^rajshahi/$',views.rajshahi,name='rajshahi'),
    url(r'^saint_martin/$',views.saint_martin,name='saint_martin'),
    url(r'^khulna/$',views.khulna,name='khulna'),
    url(r'^chittagong/$',views.chittagong,name='chittagong'),
    url(r'^dhaka/$',views.dhaka,name='dhaka'),

    url(r'^syl/$',views.syl,name='syl'),
    url(r'^khu/$',views.khu,name='khu'),
    url(r'^bar/$',views.bar,name='bar'),
    url(r'^raj/$',views.raj,name='raj'),
    url(r'^dhk/$',views.dhk,name='dhk'),
    url(r'^ctg/$',views.ctg,name='ctg'),
    url(r'^map/$',views.map,name='map'),
    url(r'^hotel/$',views.hotel,name='hotel'),


]

Project Code/community/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

Project Code/community/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','content','slug','author','status')

Project Code/community/views.py
from django.views import generic
from .models import Post
from .forms import PostForm
from django.shortcuts import render, redirect

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'community/index.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'community/post_detail.html'

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

    else:
        form = PostForm()
    return render(request, 'community/post_edit.html', {'form': form})

Project Code/templates/community/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
        <title>Community</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>
<body>
       <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
            background: url("https://farm1.staticflickr.com/726/32085594381_3f2582f61d_b.jpg");
            background-size: 100%;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: black;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>
  
          <!-- Navigation -->
        <nav class="navbar navbar-expand-lg nav " id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'homepage:index' %}" style="color: aliceblue">Unravel Bangladesh</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'menu:menu' %}" style="color: aliceblue">Destinations</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'tour:map' %}" style="color: aliceblue">Map</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'post_new' %}" style="color: aliceblue">Post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}


</body>
</html>

Project Code/templates/community/base2.html
{% load static %}
<html lang="uk">
    <head>
        <title>Community</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <style>
            .page-header {
    background-color: transparent;
    margin-top: 0;
    padding: 20px 20px 20px 40px;
}
body{
       background: url("https://farm1.staticflickr.com/726/32085594381_3f2582f61d_b.jpg");
            background-size: 100%;
}
.page-header h1, .page-header h1 a, .page-header h1 a:visited, .page-header h1 a:active {
    color: #ffffff;
    font-size: 36pt;
    text-decoration: none;
}
.content {
    margin-left: 40px;
    color: black;
}
h1,h2,h3,h4 {
    font-family: 'Lobster', cursive;
}
.date {
    color: #828282;
}
.save {
    float: right;
}
.post-form textarea, .post-form input {
    width: 100%;
}
.top-menu, .top-menu:hover, .top-menu:visited {
    color: #ffffff;
    float: right;
    font-size: 26pt;
    margin-right: 20px;
}
.post {
    margin-bottom: 70px;
}
.post h2 a, .post h2 a:visited {
    color: #000000;
}       </style>
    </head>
<body>

            <p align="top-right"> <a href="{% url 'accounts:user_login' %}" style="padding:0px;
font-size: 16px;
color: white;
text-align:center;
position: absolute;
top: 10px;
right: 10px;;z-index: 1">{{ user.username }}</a> </p>
            <h3><a href="{% url 'home' %}">Back To Community</a></h3>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

Project Code/templates/community/index.html
{% extends "community/base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    p{
        color: black; !important;
    }
    .card {
        box-shadow: 0 16px 48px black;

        background: transparent;

    }

</style>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title" style="color: black">{{ post.title }}</h2>
                    <p class="card-text text-muted h6" style="color: darkgrey">{{ post.Author }} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>

{%endblock%}

Project Code/templates/community/post_detail.html
{% extends 'community/base.html' %}
{% block content %}
<style>
    .card {
        box-shadow: 0 16px 48px black;
        background: lightcyan;
    }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Project Code/templates/community/post_edit.html
{% extends "community/base2.html" %}
{% block content %}
    {% if user.is_authenticated %}
    <h2>New post</h2>
    <form method="POST" class="post-form" id="form">
        {% csrf_token %}
        <p>{{ form.as_p }}</p>
        <button type="submit" class="save btn btn-success">Post</button>
    </form>
    {% else %}
        <h1 style="margin-top: 50px">You have to be logged in to post in the community.</h1>

    {% endif %}
{% endblock %}